# Generated by Django 4.2.7 on 2023-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('bind', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Registered'), (0, 'Not Registered')])),
                ('role_id', models.IntegerField(choices=[(0, 'Admin'), (1, 'Employee'), (2, 'Coordinator'), (3, 'Junior Manager'), (4, 'Senior Manager'), (5, 'General Manager')])),
                ('dept_id', models.IntegerField(choices=[(0, 'Admin'), (1, 'IT & Tech Product'), (2, 'Commercial'), (3, 'Finance & Human Capital'), (4, 'Operation'), (5, 'Sales')])),
            ],
        ),
    ]
