# Generated by Django 4.2.7 on 2023-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Success')])),
                ('attendance_date', models.DateField()),
                ('attendance_in_time', models.DateTimeField()),
                ('attendance_in_date', models.DateField()),
                ('attendance_out_time', models.DateTimeField()),
                ('attendance_out_date', models.DateField()),
                ('working_hours', models.DurationField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_id', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
