# Generated by Django 4.2.7 on 2023-11-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0005_user_nik_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='nik',
            field=models.IntegerField(default=0),
        ),
    ]
