# Generated by Django 4.2.7 on 2023-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0006_faceimage_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bind',
            field=models.BooleanField(default=False),
        ),
    ]
