# Generated by Django 4.2.7 on 2023-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0007_alter_user_bind'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
