# Generated by Django 4.2.7 on 2024-02-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0009_officemaster_rolemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemaster',
            name='admin_menu',
        ),
    ]
