# Generated by Django 4.2.7 on 2024-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0010_remove_rolemaster_admin_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemaster',
            old_name='register_member',
            new_name='register_employee',
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='settings_employee',
            field=models.BooleanField(default=False),
        ),
    ]
