# Generated by Django 4.2.7 on 2024-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0013_attendancelog_attendance_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceStatusMaster',
            fields=[
                ('presence_id', models.AutoField(primary_key=True, serialize=False)),
                ('presence_code', models.CharField(max_length=10, unique=True)),
                ('presence_name', models.CharField(max_length=100)),
            ],
        ),
    ]
