# Generated by Django 4.2.7 on 2024-02-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0014_presencestatusmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance_in_date',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance_out_date',
        ),
    ]
