# Generated by Django 4.2.7 on 2024-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0015_remove_attendancelog_attendance_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='presence_status',
            field=models.IntegerField(default=0),
        ),
    ]
