# Generated by Django 4.2.7 on 2024-02-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0016_attendancelog_presence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='attendance_in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='attendance_out_time',
            field=models.TimeField(),
        ),
    ]
