# Generated by Django 4.2.7 on 2024-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0017_alter_attendancelog_attendance_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='attendance_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
