# Generated by Django 4.2.7 on 2024-02-23 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0018_alter_attendancelog_attendance_out_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='latitude',
            new_name='latitude_in',
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='longitude',
            new_name='latitude_out',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude_in',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude_out',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
