# Generated by Django 4.2.7 on 2024-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0019_rename_latitude_attendancelog_latitude_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='latitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='longitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
