# Generated by Django 4.2.7 on 2024-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0020_alter_attendancelog_latitude_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='presence_status',
            field=models.CharField(max_length=5),
        ),
    ]
