# Generated by Django 4.2.7 on 2024-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0022_alter_attendancelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='presence_status',
            field=models.CharField(max_length=10),
        ),
    ]
