# Generated by Django 4.2.7 on 2024-02-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0023_alter_attendancelog_presence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='status',
        ),
    ]
