# Generated by Django 4.2.7 on 2024-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0024_remove_attendancelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
