# Generated by Django 4.2.7 on 2024-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0025_attendancelog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='status',
            new_name='attendance_in_status',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance_in',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance_out',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='attendance_office',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
