# Generated by Django 4.2.7 on 2024-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0026_rename_status_attendancelog_attendance_in_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
