# Generated by Django 4.2.7 on 2024-02-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0028_attendancelog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
