# Generated by Django 4.2.7 on 2024-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceproject', '0029_remove_attendancelog_nik_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='nik',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
